version: '3.7'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      - ZOOKEEPER_TICK_TIME=2000 \
      - ZOOKEEPER_CLIENT_PORT=2181
    volumes:
      - zookeeper-data1:/var/lib/zookeeper/data
      - zookeeper-transaction-logs1:/var/lib/zookeeper/log
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:5.2.1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # This configuration is based on https://rmoff.net/2018/08/02/kafka-listeners-explained/
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER://kafka:29092,LISTENER_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=20
    volumes:
      - kafka-data1:/var/lib/kafka/data
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  zipkin:
    image: openzipkin/zipkin:2.12.6
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g
      - ZIPKIN_UI_ENVIRONMENT=localhost
    ports:
      - 9411:9411

volumes:
  kafka-data1:
    driver: local
  zookeeper-data1:
    driver: local
  zookeeper-transaction-logs1:
    driver: local
