server:
  port: 8080

spring:
  application:
    name: kafka-producer
  sleuth:
    enabled: true
    traceId128: true
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411
